version: '3.5'
services:
  myapplication:
    build:
      context: ./api
      args:
       - COMMIT_SHA=$COMMIT_SHA
       - GIT_TAG=$GIT_TAG
    ports:
       - "127.0.0.1:8001:8001"
    environment:
       - PORT=8001
       - LOG_LEVEL=INFO
    container_name: anz_master